name: Yakindu SCT C++11 Timer Service.
on: [push]

jobs:
   CPP-Check:
      runs-on: ubuntu-latest
      steps:
         - run: sudo apt update -y
         - run: sudo apt install -y qt5-qmake
         - run: echo "Hi!"
         - run: ls -l
         

