name: Yakindu SCT C++11 Timer Service.
on: [push]

jobs:
   CPP-Check:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - run: sudo apt update -y
         - run: sudo apt install -y qt5-qmake
         - run: ls -l
         - run: bin/jenkins.sh
