name: Yakindu SCT C++11 Timer Service.
on: [push]

jobs:
   CPP-Check:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Prepare
           run: sudo apt update -y
           run: sudo apt install -y qt5-qmake
         - name: Show
           run: echo "Hi!"
           run: ls -l
         - name: Build
           run: bin/jenkins.sh
